server:
  port: 8084

spring:
  application:
    name: security
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.199.244:3306/simple_blog?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: gorylee
    password: 123456

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl