server:
  port: 8088

spring:
  application:
    name: spring-batch-demo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn_demo?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    maximum-pool-size: 20
  batch:
    job:
      enabled: false

job:
  data:
    path: D:\workCode2\learnDemo\

xxl:
  job:
    admin:
      addresses: http://localhost:8022/xxl-job-admin
    accessToken: default_token777
    executor:
      appname: spring-batch-demo
      address:
      ip:
      port: 8890
      logpath:
      logretentiondays: 30

# 日志
logging:
  config: classpath:config/logback-spring.xml

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
